version: '3'
services:
  app:
    image: benjabkn01/black-joaco:latest
    build: .
    ports:
      - "${PORT}:${PORT}"  # Usa el puerto especificado en .env
    environment:
      - MONGODB_URI=${MONGODB_URI}  # Usa la URI de MongoDB desde .env
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
